name: release-1

on: 
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.git-cliff.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          #args: --verbose
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      #- name: Print the changelog
      #  run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Upload CHANGELOG.md
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  zip-files:
    runs-on: ubuntu-latest
    needs: changelog
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: 'src/python/manifest.json'
          placeholder: '${VERSION}'

      - name: Create zip
        uses: papeloto/action-zip@v1
        with:
          files: src/python readme.md
          dest: release.zip
          recursive: true

      #- name: Changelog
      #  uses: scottbrenner/generate-changelog-action@master
      #  id: Changelog

      - name: Download CHANGELOG.md
        uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "ManageAppProjects.zip"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}